### ISSUE TITLE
I'm trying to use this with a Svelte project and I get an error

### ISSUE THREAD

**Issue by Evertt** [keithamus/rollup-plugin-brotli#6]
The error goes:

```
[!] (plugin brotli) TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:327:9)
    at isCompressed (/Users/evert/Sites/svelte-sd/node_modules/rollup-plugin-brotli/lib/index.cjs.js:20:74)
    at /Users/evert/Sites/svelte-sd/node_modules/rollup-plugin-brotli/lib/index.cjs.js:64:69
    at Array.filter (<anonymous>)
    at Object.writeBundle (/Users/evert/Sites/svelte-sd/node_modules/rollup-plugin-brotli/lib/index.cjs.js:64:53)
    at /Users/evert/Sites/svelte-sd/node_modules/rollup/dist/shared/rollup.js:17846:25
    at async Promise.all (index 0)
    at /Users/evert/Sites/svelte-sd/node_modules/rollup/dist/shared/rollup.js:18620:17
    at async Promise.all (index 0)
    at build (/Users/evert/Sites/svelte-sd/node_modules/rollup/dist/bin/rollup:1480:5)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 build: `routify -bD && NODE_ENV=production rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/evert/.npm/_logs/2020-05-14T17_18_10_021Z-debug.log
```

The log file doesn't seem to contain any useful info. Do you have any idea what might be going on? I'm including the brotli plugin without any config, just `brotli()`.

**Comment by keithamus** [comment]
@Evertt could you please try `rollup-plugin-brotli@3.0.0`. Thanks!

**Comment by keithamus** [comment]
I'm going to close this as there's been no activity on this issue, and it's likely the latest version fixes this.
